calendar:
  NAME: "Rec Center Calendar"
  URL: "https://calendar.google.com/calendar/ical/gtodk5h2aqt0kk7ofr9ra2q7mk%40group.calendar.google.com/public/basic.ics"
  TIMEZONE: "America/Los_Angeles"
  WEEK_STARTS_ON: "Sunday"

docx:
  PAPER_SIZE_HEIGHT: 11
  PAPER_SIZE_WIDTH: 17
  MARGIN_SIZE: 0.25
  FONT_CHOICE: "Arial"
  CAL_FONT_SIZE: 9
  HEADER_FONT_SIZE: 26
  TABLE_STYLE: "Table Grid"
  UNDERLINE_BOOL: true
  UNDERLINE_START_TIME: 1800
  UNDERLINE_END_TIME: 2359

# for reportlab python library
pdf:
  PAPER_SIZE_HEIGHT: 11
  PAPER_SIZE_WIDTH: 17
  MARGIN_SIZE: 0.25
  FONT_CHOICE: "Arial"
  CAL_FONT_SIZE: 9
  HEADER_FONT_SIZE: 26
  UNDERLINE_BOOL: true
  UNDERLINE_START_TIME: 1800
  UNDERLINE_END_TIME: 2359

# easy names for hex values for the color choices for the different locations 
colors:
  # pastel colors
  - name: "Dark Orange"
    hex: "#FD7F03"
  - name: "Red"
    hex: "#FC0107"
  - name: "Blue"  
    hex: "#4F81BD"
  - name: "Green" 
    hex: "#269644"
  - name: "Purple" 
    hex: "#7030A0"
  - name: "Pink"
    hex: "#FC02FF"
  - name: "Brown"
    hex: "#974706"
  - name: "Gray"
    hex: "#7B8EB5"
  - name: "Lavender"
    hex: "#A7A7A7"
  - name: "Light Green"
    hex: "#B7E1CD"
  - name: "Light Blue"
    hex: "#B4C6E7"
  - name: "Light Yellow"
    hex: "#FFD966"
  - name: "Light Orange"


locations:
  - Name: "Art Studio"
    Color: "Dark Orange"
    Short: "ART"
    Alt: ["Art Room", "Art"]
  - Name: "Kitchen"
    Color: "Red"
    Short: "FOOD"
    Alt: ["Kitchen", "Cooking Lab", "kitchen"]
  - Name: "Woodshop"
    Color: "Brown"
    Short: "WOOD"
    Alt: ["Woodworking Studio", "Wood Shop", "Wood"]
  - Name: "Greenhouse"
    Color: "Green"
    Short: "GRN"
    Alt: ["Green House", "Green house", "green"]
  - Name: "STEM Lab"
    Color: "Blue"
    Short: "STEM"
    Alt: ["STEM", "Maker Space", "Maker space"]
  - Name: "Science Room"
    Color: "Purple"
    Short: "SCI"
    Alt: ["Science Room", "Science Studio", "Science", "Sci"]
  - Name: "Theater"
    Color: "Pink"
    Short: "THTR"
    Alt: ["Theater", "stage", "theater"]
  - Name: "Lobby"
    Color: "Gray"
    Short: "LBBY"
    Alt: ["lobby", "hallway", "Hallway", "entrance", "Entrance"]
  - Name: "Library"
    Color: "Lavender"
    Short: "LIB"
    Alt: ["library", "book place", "reading room"]
  - Name: "Meeting Room"
    Color: "Light Blue"
    Short: "MEET"
    Alt: ["meeting", "meeting Room", "Meeting room"]
